# encoding: UTF-8

FROM <%= ENV.fetch('FROM') %>
MAINTAINER The Blue Beluga <admin@bluebeluga.io>

LABEL vendor="The Blue Beluga Company"
LABEL io.bluebeluga.jdk.description="Oracle JDK"
LABEL io.bluebeluga.jdk.version="<%= ENV.fetch('TAG') %>"
LABEL io.bluebeluga.jdk.git-revision="<%= ENV.fetch('GIT_REVISION') %>"
LABEL io.bluebeluga.jdk.release-date="<%= Time.now.strftime('%B %d, %Y %H:%M') %>"

ENV JDK_VERSION <%= ENV.fetch('JDK_VERSION') %>
ENV JDK_UPDATE <%= ENV.fetch('JDK_UPDATE') %>
ENV JDK_BUILD <%= ENV.fetch('JDK_BUILD') %>
ENV JDK_PACKAGE <%= ENV.fetch('JDK_PACKAGE') %>
ENV JDK_SHA256 <%= ENV.fetch('JDK_SHA256') %>
ENV JDK_HOME <%= ENV.fetch('JDK_HOME') %>

RUN apk add --no-cache --virtual=build-dependencies curl ca-certificates tar && \
    mkdir -p /opt && \
    curl -jkLH "Cookie: oraclelicense=accept-securebackup-cookie" -o java.tar.gz \
               "http://download.oracle.com/otn-pub/java/jdk/${JDK_VERSION}u${JDK_UPDATE}-b${JDK_BUILD}/${JDK_PACKAGE}-${JDK_VERSION}u${JDK_UPDATE}-linux-x64.tar.gz" && \
    echo "${JDK_SHA256}  java.tar.gz" | sha256sum -c - && \
    gunzip -c java.tar.gz | tar -xf - -C /opt && \
    rm -f java.tar.gz && \
    ln -s "${JDK_HOME}1.${JDK_VERSION}.0_${JDK_UPDATE}" "${JDK_HOME}" && \
    rm -rf "${JDK_HOME}/*src.zip" \
           "${JDK_HOME}/lib/missioncontrol" \
           "${JDK_HOME}/lib/visualvm" \
           "${JDK_HOME}/lib/*javafx*" \
           "${JDK_HOME}/jre/lib/plugin.jar" \
           "${JDK_HOME}/jre/lib/ext/jfxrt.jar" \
           "${JDK_HOME}/jre/bin/javaws" \
           "${JDK_HOME}/jre/lib/javaws.jar" \
           "${JDK_HOME}/jre/lib/desktop" \
           "${JDK_HOME}/jre/plugin" \
           "${JDK_HOME}/jre/lib/deploy*" \
           "${JDK_HOME}/jre/lib/*javafx*" \
           "${JDK_HOME}/jre/lib/*jfx*" \
           "${JDK_HOME}/jre/lib/amd64/libdecora_sse.so" \
           "${JDK_HOME}/jre/lib/amd64/libprism_*.so" \
           "${JDK_HOME}/jre/lib/amd64/libfxplugins.so" \
           "${JDK_HOME}/jre/lib/amd64/libglass.so" \
           "${JDK_HOME}/jre/lib/amd64/libgstreamer-lite.so" \
           "${JDK_HOME}/jre/lib/amd64/libjavafx*.so" \
           "${JDK_HOME}/jre/lib/amd64/libjfx*.so" && \
    apk del build-dependencies && \
    rm -rf /var/cache/apk/*

ENV PATH "${JDK_HOME}/bin:${PATH}"
